[project]
name = "mt-evaluation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "huggingface-hub[cli]>=0.26.5",
    "polars>=1.8.2",
]
